export const States = [
  {
    state: "Abia",
    code: "AB",
    lgas: [
      { name: "Aba North" },
      { name: "Aba South" },
      { name: "Arochukwu" },
      { name: "Bende" },
      { name: "Ikwuano" },
      { name: "Isiala Ngwa North" },
      { name: "Isiala Ngwa South" },
      { name: "Isuikwuato" },
      { name: "Obi Ngwa" },
      { name: "Ohafia" },
      { name: "Osisioma" },
      { name: "Ugwunagbo" },
      { name: "Ukwa East" },
      { name: "Ukwa West" },
      { name: "Umu Nneochi" },
      { name: "Umuahia North" },
      { name: "Umuahia South" },
    ],
  },
  {
    state: "Adamawa",
    code: "AD",
    lgas: [
      { name: "Demsa" },
      { name: "Fufore" },
      { name: "Ganye" },
      { name: "Girei" },
      { name: "Gombi" },
      { name: "Guyuk" },
      { name: "Hong" },
      { name: "Jada" },
      { name: "Lamurde" },
      { name: "Madagali" },
      { name: "Maiha" },
      { name: "Mayo-Belwa" },
      { name: "Michika" },
      { name: "Mubi North" },
      { name: "Mubi South" },
      { name: "Numan" },
      { name: "Shelleng" },
      { name: "Song" },
      { name: "Toungo" },
      { name: "Yola North" },
      { name: "Yola South" },
    ],
  },
  {
    state: "Akwa Ibom",
    code: "AK",
    lgas: [
      { name: "Abak" },
      { name: "Eastern Obolo" },
      { name: "Eket" },
      { name: "Esit Eket" },
      { name: "Essien Udim" },
      { name: "Etim Ekpo" },
      { name: "Etinan" },
      { name: "Ibeno" },
      { name: "Ibesikpo Asutan" },
      { name: "Ibiono-Ibom" },
      { name: "Ika" },
      { name: "Ikono" },
      { name: "Ikot Abasi" },
      { name: "Ikot Ekpene" },
      { name: "Ini" },
      { name: "Itu" },
      { name: "Mbo" },
      { name: "Mkpat-Enin" },
      { name: "Nsit-Atai" },
      { name: "Nsit-Ibom" },
      { name: "Nsit-Ubium" },
      { name: "Obot Akara" },
      { name: "Okobo" },
      { name: "Onna" },
      { name: "Oron" },
      { name: "Oruk Anam" },
      { name: "Udung-Uko" },
      { name: "Ukanafun" },
      { name: "Uruan" },
      { name: "Urue-Offong/Oruko" },
      { name: "Uyo" },
    ],
  },
  {
    state: "Anambra",
    code: "AN",
    lgas: [
      { name: "Aguata" },
      { name: "Anambra East" },
      { name: "Anambra West" },
      { name: "Anaocha" },
      { name: "Awka North" },
      { name: "Awka South" },
      { name: "Ayamelum" },
      { name: "Dunukofia" },
      { name: "Ekwusigo" },
      { name: "Idemili North" },
      { name: "Idemili South" },
      { name: "Ihiala" },
      { name: "Njikoka" },
      { name: "Nnewi North" },
      { name: "Nnewi South" },
      { name: "Ogbaru" },
      { name: "Onitsha North" },
      { name: "Onitsha South" },
      { name: "Orumba North" },
      { name: "Orumba South" },
      { name: "Oyi" },
    ],
  },
  {
    state: "Bauchi",
    code: "BA",
    lgas: [
      { name: "Alkaleri" },
      { name: "Bauchi" },
      { name: "Bogoro" },
      { name: "Damban" },
      { name: "Darazo" },
      { name: "Dass" },
      { name: "Gamawa" },
      { name: "Ganjuwa" },
      { name: "Giade" },
      { name: "Itas/Gadau" },
      { name: "Jama'are" },
      { name: "Katagum" },
      { name: "Kirfi" },
      { name: "Misau" },
      { name: "Ningi" },
      { name: "Shira" },
      { name: "Tafawa Balewa" },
      { name: "Toro" },
      { name: "Warji" },
      { name: "Zaki" },
    ],
  },
  {
    state: "Bayelsa",
    code: "BY",
    lgas: [
      { name: "Brass" },
      { name: "Ekeremor" },
      { name: "Kolokuma/Opokuma" },
      { name: "Nembe" },
      { name: "Ogbia" },
      { name: "Sagbama" },
      { name: "Southern Ijaw" },
      { name: "Yenagoa" },
    ],
  },
  {
    state: "Benue",
    code: "BN",
    lgas: [
      { name: "Ado" },
      { name: "Agatu" },
      { name: "Apa" },
      { name: "Buruku" },
      { name: "Gboko" },
      { name: "Guma" },
      { name: "Gwer East" },
      { name: "Gwer West" },
      { name: "Katsina-Ala" },
      { name: "Konshisha" },
      { name: "Kwande" },
      { name: "Logo" },
      { name: "Makurdi" },
      { name: "Obi" },
      { name: "Ogbadibo" },
      { name: "Ohimini" },
      { name: "Oju" },
      { name: "Okpokwu" },
      { name: "Otukpo" },
      { name: "Tarka" },
      { name: "Ukum" },
      { name: "Ushongo" },
      { name: "Vandeikya" },
    ],
  },
  {
    state: "Borno",
    code: "BO",
    lgas: [
      { name: "Abadam" },
      { name: "Askira/Uba" },
      { name: "Bama" },
      { name: "Bayo" },
      { name: "Biu" },
      { name: "Chibok" },
      { name: "Damboa" },
      { name: "Dikwa" },
      { name: "Gubio" },
      { name: "Guzamala" },
      { name: "Gwoza" },
      { name: "Hawul" },
      { name: "Jere" },
      { name: "Kaga" },
      { name: "Kala/Balge" },
      { name: "Konduga" },
      { name: "Kukawa" },
      { name: "Kwaya Kusar" },
      { name: "Mafa" },
      { name: "Magumeri" },
      { name: "Maiduguri" },
      { name: "Marte" },
      { name: "Mobbar" },
      { name: "Monguno" },
      { name: "Ngala" },
      { name: "Nganzai" },
      { name: "Shani" },
    ],
  },
  {
    state: "Cross River",
    code: "CR",
    lgas: [
      { name: "Abi" },
      { name: "Akamkpa" },
      { name: "Akpabuyo" },
      { name: "Bakassi" },
      { name: "Bekwarra" },
      { name: "Biase" },
      { name: "Boki" },
      { name: "Calabar Municipal" },
      { name: "Calabar South" },
      { name: "Etung" },
      { name: "Ikom" },
      { name: "Obanliku" },
      { name: "Obubra" },
      { name: "Odukpani" },
      { name: "Okpoku" },
      { name: "Ogoja" },
      { name: "Yala" },
    ],
  },
  {
    state: "Delta",
    code: "DE",
    lgas: [
      { name: "Aniocha North" },
      { name: "Aniocha South" },
      { name: "Bomadi" },
      { name: "Burutu" },
      { name: "Delta North" },
      { name: "Delta Central" },
      { name: "Delta South" },
      { name: "Ethiope East" },
      { name: "Ethiope West" },
      { name: "Ika North East" },
      { name: "Ika South" },
      { name: "Okpe" },
      { name: "Oshimili North" },
      { name: "Oshimili South" },
      { name: "Ovia North-East" },
      { name: "Ovia South-West" },
      { name: "Patani" },
      { name: "Sapele" },
      { name: "Udu" },
      { name: "Ughelli North" },
      { name: "Ughelli South" },
      { name: "Ukwuani" },
      { name: "Warri North" },
      { name: "Warri South" },
      { name: "Warri South West" },
    ],
  },
  {
    state: "Ebonyi",
    code: "EB",
    lgas: [
      { name: "Abakaliki" },
      { name: "Afikpo North" },
      { name: "Afikpo South" },
      { name: "Ebonyi" },
      { name: "Ezza North" },
      { name: "Ezza South" },
      { name: "Ishielu" },
      { name: "Ivo" },
      { name: "Onicha" },
    ],
  },
  {
    state: "Edo",
    code: "ED",
    lgas: [
      { name: "Akoko Edo" },
      { name: "Egor" },
      { name: "Esan Central" },
      { name: "Esan North-East" },
      { name: "Esan South-East" },
      { name: "Esan West" },
      { name: "Oredo" },
      { name: "Orhionmwon" },
      { name: "Ovia North-East" },
      { name: "Ovia South-West" },
      { name: "Uhunmwonde" },
    ],
  },
  {
    state: "Ekiti",
    code: "EK",
    lgas: [
      { name: "Ado Ekiti" },
      { name: "Ekiti East" },
      { name: "Ekiti South-West" },
      { name: "Ekiti West" },
      { name: "Emure" },
      { name: "Irepodun/Ifelodun" },
      { name: "Ise/Orun" },
      { name: "Moba" },
      { name: "Oye" },
    ],
  },
  {
    state: "Enugu",
    code: "EN",
    lgas: [
      { name: "Agwu" },
      { name: "Awgu" },
      { name: "Enugu East" },
      { name: "Enugu North" },
      { name: "Enugu South" },
      { name: "Ezeagu" },
      { name: "Igbo-Etiti" },
      { name: "Igbo-Eze North" },
      { name: "Igbo-Eze South" },
      { name: "Isi-Uzo" },
      { name: "Nkanu East" },
      { name: "Nkanu West" },
      { name: "Nsukka" },
      { name: "Oji River" },
      { name: "Udenu" },
      { name: "Udi" },
      { name: "Uzo-Uwani" },
    ],
  },
  {
    state: "Gombe",
    code: "GO",
    lgas: [
      { name: "Akko" },
      { name: "Balanga" },
      { name: "Billiri" },
      { name: "Dukku" },
      { name: "Funakaye" },
      { name: "Gombe" },
      { name: "Kaltungo" },
      { name: "Kwami" },
      { name: "Nafada" },
      { name: "Shongom" },
      { name: "Yamaltu/Deba" },
    ],
  },
  {
    state: "Imo",
    code: "IM",
    lgas: [
      { name: "Aboh Mbaise" },
      { name: "Ahiazu Mbaise" },
      { name: "Ikeduru" },
      { name: "Isu" },
      { name: "Mbaitoli" },
      { name: "Ngor Okpala" },
      { name: "Njaba" },
      { name: "Nkwerre" },
      { name: "Obowo" },
      { name: "Oguta" },
      { name: "Ohaji/Egbema" },
      { name: "Okigwe" },
      { name: "Orlu" },
      { name: "Orsu" },
      { name: "Owerri Municipal" },
      { name: "Owerri North" },
      { name: "Owerri West" },
    ],
  },
  {
    state: "Jigawa",
    code: "JI",
    lgas: [
      { name: "Auyo" },
      { name: "Babura" },
      { name: "Birnin Kudu" },
      { name: "Buji" },
      { name: "Dukku" },
      { name: "Garki" },
      { name: "Gumel" },
      { name: "Guri" },
      { name: "Hadejia" },
      { name: "Jahun" },
      { name: "Kafin Hausa" },
      { name: "Kazaure" },
      { name: "Kirikasamma" },
      { name: "Maigatari" },
      { name: "Malam Madori" },
      { name: "Miga" },
      { name: "Ringim" },
      { name: "Roni" },
      { name: "Sule Tankarkar" },
      { name: "Yankwashi" },
    ],
  },
  {
    state: "Kano",
    code: "KA",
    lgas: [
      { name: "Ajingi" },
      { name: "Albasu" },
      { name: "Bagwai" },
      { name: "Bebeji" },
      { name: "Bichi" },
      { name: "Dala" },
      { name: "Dawakin Kudu" },
      { name: "Dawakin Tofa" },
      { name: "Doguwa" },
      { name: "Fagge" },
      { name: "Gaya" },
      { name: "Garko" },
      { name: "Karaye" },
      { name: "Kibiya" },
      { name: "Kiru" },
      { name: "Kumbotso" },
      { name: "Lagos" },
      { name: "Nassarawa" },
      { name: "Rogo" },
      { name: "Shanono" },
      { name: "Tarauni" },
      { name: "Tofa" },
      { name: "Tsanyawa" },
      { name: "Ungogo" },
      { name: "Warawa" },
      { name: "Wudil" },
    ],
  },
  {
    state: "Kogi",
    code: "KO",
    lgas: [
      { name: "Adavi" },
      { name: "Ajaokuta" },
      { name: "Ankpa" },
      { name: "Bassa" },
      { name: "Dekina" },
      { name: "Ibaji" },
      { name: "Idah" },
      { name: "Igalamela-Odolu" },
      { name: "Ogori/Magongo" },
      { name: "Okehi" },
      { name: "Okene" },
      { name: "Omala" },
      { name: "Onoja" },
      { name: "Yagba East" },
      { name: "Yagba West" },
    ],
  },
  {
    state: "Kwara",
    code: "KW",
    lgas: [
      { name: "Asa" },
      { name: "Baruten" },
      { name: "Edu" },
      { name: "Ekiti" },
      { name: "Ifelodun" },
      { name: "Ilorin East" },
      { name: "Ilorin South" },
      { name: "Ilorin West" },
      { name: "Moro" },
      { name: "Oke Ero" },
      { name: "Offa" },
      { name: "Oyun" },
    ],
  },
  {
    state: "Lagos",
    code: "LA",
    lgas: [
      { name: "Agege" },
      { name: "Ajeromi Ifelodun" },
      { name: "Alimosho" },
      { name: "Apapa" },
      { name: "Badagry" },
      { name: "Epe" },
      { name: "Eti Osa" },
      { name: "Ibeju Lekki" },
      { name: "Ifako/Ijaye" },
      { name: "Ikeja" },
      { name: "Ikorodu" },
      { name: "Lagos Mainland" },
      { name: "Lagos Island" },
      { name: "Mushin" },
      { name: "Ojo" },
      { name: "Oshodi/Isolo" },
      { name: "Somolu" },
      { name: "Surulere" },
    ],
  },
  {
    state: "Nasarawa",
    code: "NA",
    lgas: [
      { name: "Akwanga" },
      { name: "Doma" },
      { name: "Keffi" },
      { name: "Kokona" },
      { name: "Nasarawa" },
      { name: "Obi" },
      { name: "Toto" },
      { name: "Wamba" },
    ],
  },
  {
    state: "Niger",
    code: "NI",
    lgas: [
      { name: "Agaie" },
      { name: "Agwara" },
      { name: "Bida" },
      { name: "Borgu" },
      { name: "Bosso" },
      { name: "Chanchaga" },
      { name: "Edati" },
      { name: "Gbako" },
      { name: "Gurara" },
      { name: "Katcha" },
      { name: "Kontagora" },
      { name: "Mashegu" },
      { name: "Mokwa" },
      { name: "Paikoro" },
      { name: "Rafi" },
      { name: "Shiroro" },
      { name: "Suleja" },
    ],
  },
  {
    state: "Ogun",
    code: "OG",
    lgas: [
      { name: "Abeokuta North" },
      { name: "Abeokuta South" },
      { name: "Ado-Odo/Ota" },
      { name: "Egbado North" },
      { name: "Egbado South" },
      { name: "Ifo" },
      { name: "Ijebu East" },
      { name: "Ijebu North" },
      { name: "Ijebu North East" },
      { name: "Ijebu Ode" },
      { name: "Obafemi Owode" },
      { name: "Odeda" },
      { name: "Ogun Waterside" },
      { name: "Remo North" },
      { name: "Sagamu" },
      { name: "Yewa North" },
      { name: "Yewa South" },
    ],
  },
  {
    state: "Ondo",
    code: "ON",
    lgas: [
      { name: "Akoko North-East" },
      { name: "Akoko North-West" },
      { name: "Akoko South-East" },
      { name: "Akoko South-West" },
      { name: "Ese Odo" },
      { name: "Idanre" },
      { name: "Ifedore" },
      { name: "Odigbo" },
      { name: "Ose" },
      { name: "Ondo East" },
      { name: "Ondo West" },
      { name: "Owo" },
    ],
  },
  {
    state: "Osun",
    code: "OS",
    lgas: [
      { name: "Aiyedaade" },
      { name: "Aiyedire" },
      { name: "Atakunmosa East" },
      { name: "Atakunmosa West" },
      { name: "Boripe" },
      { name: "Ede North" },
      { name: "Ede South" },
      { name: "Egbedore" },
      { name: "Ife Central" },
      { name: "Ife East" },
      { name: "Ife North" },
      { name: "Ife South" },
      { name: "Ilesa East" },
      { name: "Ilesa West" },
      { name: "Isokan" },
      { name: "Obokun" },
      { name: "Oriade" },
      { name: "Orolu" },
      { name: "Osogbo" },
    ],
  },
  {
    state: "Oyo",
    code: "OY",
    lgas: [
      { name: "Akinyele" },
      { name: "Atiba" },
      { name: "Atisbo" },
      { name: "Egbeda" },
      { name: "Ibadan East" },
      { name: "Ibadan North" },
      { name: "Ibadan North-East" },
      { name: "Ibadan North-West" },
      { name: "Ibadan South-East" },
      { name: "Ibadan South-West" },
      { name: "Ibarapa Central" },
      { name: "Ibarapa East" },
      { name: "Ibarapa North" },
      { name: "Ido" },
      { name: "Lagelu" },
      { name: "Oyo East" },
      { name: "Oyo West" },
    ],
  },
  {
    state: "Plateau",
    code: "PL",
    lgas: [
      { name: "Bokkos" },
      { name: "Jos East" },
      { name: "Jos North" },
      { name: "Jos South" },
      { name: "Kanam" },
      { name: "Langtang North" },
      { name: "Langtang South" },
      { name: "Mangu" },
      { name: "Pankshin" },
      { name: "Quaan Pan" },
      { name: "Riyom" },
      { name: "Shendam" },
      { name: "Wase" },
    ],
  },
  {
    state: "Rivers",
    code: "RI",
    lgas: [
      { name: "Abua/Odual" },
      { name: "Ahoada East" },
      { name: "Ahoada West" },
      { name: "Akuku-Toru" },
      { name: "Asari-Toru" },
      { name: "Bonny" },
      { name: "Degema" },
      { name: "Emohua" },
      { name: "Etche" },
      { name: "Ikwerre" },
      { name: "Obio/Akpor" },
      { name: "Ogba/Egbema/Ndoni" },
      { name: "Ogu/Bolo" },
      { name: "Okrika" },
      { name: "Omuma" },
      { name: "Port Harcourt" },
      { name: "Tai" },
    ],
  },
  {
    state: "Sokoto",
    code: "SO",
    lgas: [
      { name: "Bagudo" },
      { name: "Bodinga" },
      { name: "Dange Shuni" },
      { name: "Gada" },
      { name: "Goronyo" },
      { name: "Gudu" },
      { name: "Illela" },
      { name: "Kebbe" },
      { name: "Kware" },
      { name: "Rabah" },
      { name: "Sabon Birni" },
      { name: "Shagari" },
      { name: "Silame" },
      { name: "Sokoto North" },
      { name: "Sokoto South" },
      { name: "Wamako" },
    ],
  },
  {
    state: "Taraba",
    code: "TA",
    lgas: [
      { name: "Ardo Kola" },
      { name: "Bali" },
      { name: "Donga" },
      { name: "Gashaka" },
      { name: "Gassol" },
      { name: "Ibi" },
      { name: "Jalingo" },
      { name: "Kalma" },
      { name: "Lau" },
      { name: "Nguroje" },
      { name: "Sardauna" },
      { name: "Ussa" },
      { name: "Wukari" },
      { name: "Yorro" },
    ],
  },
  {
    state: "Yobe",
    code: "YO",
    lgas: [
      { name: "Bade" },
      { name: "Bursari" },
      { name: "Damaturu" },
      { name: "Fika" },
      { name: "Fune" },
      { name: "Geidam" },
      { name: "Nguru" },
      { name: "Potiskum" },
      { name: "Tarmuwa" },
      { name: "Yunusari" },
      { name: "Yobe" },
    ],
  },
  {
    state: "Zamfara",
    code: "ZA",
    lgas: [
      { name: "Anka" },
      { name: "Bakura" },
      { name: "Birnin Magaji" },
      { name: "Bukkuyum" },
      { name: "Gummi" },
      { name: "Maradun" },
      { name: "Shinkafi" },
      { name: "Talata Mafara" },
      { name: "Zamfara" },
    ],
  },
];
