export const states = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const locationsByState = [
  "balogun",
  "ikorodu",
  "agege",
  "ikotun",
  "mushin",
  "Mile12",
  "relief",
  "ochanja",
  "main-mkt",
  "agbeni",
  "ilorin",
  "cemetry-market",
  "mile1",
  "mile3",
  "benin",
  "uyo",
  "sabongari",
  "sokoto",
  "jos",
  "abuja",
  "central-market",
  "Aba North",
  "Aba South",
  "Arochukwu",
  "Bende",
  "Ikwuano",
  "Isiala Ngwa North",
  "Isiala Ngwa South",
  "Isuikwuato",
  "Obingwa",
  "Ohafia",
  "Osisioma Ngwa",
  "Ugwunagbo",
  "Umuneochi",
  "Ukwa East",
  "Ukwa West",
  "Demsa",
  "Fufore",
  "Ganye",
  "Girei",
  "Gombi",
  "Hong",
  "Jada",
  "Lamurde",
  "Mubi North",
  "Mubi South",
  "Numan",
  "Shelleng",
  "Song",
  "Toungo",
  "Yola North",
  "Abak",
  "Eastern Obolo",
  "Eket",
  "Esit Eket",
  "Etim Ekpo",
  "Etinan",
  "Ibeno",
  "Ibiono Ibom",
  "Ika",
  "Ikono",
  "Ikot Abasi",
  "Ikot Ekpene",
  "Obot Akara",
  "Onna",
  "Oron",
  "Ukanafun",
  "Uruan",
  "Urue-Offong/Oruko",
  "Ikot Ekpene",
  "Aguata",
  "Anambra East",
  "Anambra West",
  "Awka North",
  "Awka South",
  "Ayamelum",
  "Dunukofia",
  "Ekwusigo",
  "Idemili North",
  "Idemili South",
  "Ihiala",
  "Njikoka",
  "Nnewi North",
  "Nnewi South",
  "Ogbaru",
  "Onitsha North",
  "Onitsha South",
  "Orumba North",
  "Orumba South",
  "Oyi",
  "Alkaleri",
  "Bauchi",
  "Bogoro",
  "Dambam",
  "Darazo",
  "Dass",
  "Elisha",
  "Gamawa",
  "Ganjuwa",
  "Kirfi",
  "Misau",
  "Ningi",
  "Shira",
  "Tafawa Balewa",
  "Toro",
  "Warji",
  "Zaki",
  "Brass",
  "Ekeremor",
  "Kolokuma/Opokuma",
  "Nembe",
  "Ogbia",
  "Sagbama",
  "Southern Ijaw",
  "Yenagoa",
  "Ado",
  "Agatu",
  "Apa",
  "Bokkos",
  "Buruku",
  "Gboko",
  "Guma",
  "Gwer East",
  "Gwer West",
  "Katsina-Ala",
  "Konshisha",
  "Makurdi",
  "Obi",
  "Ogbadibo",
  "Ohimini",
  "Oju",
  "Otukpo",
  "Tarka",
  "Ukum",
  "Vandeikya",
  "Abadam",
  "Askira/Uba",
  "Bayo",
  "Biu",
  "Chibok",
  "Damboa",
  "Dikwa",
  "Gubio",
  "Guzamala",
  "Hawul",
  "Jere",
  "Kaga",
  "Kala/Balge",
  "Konduga",
  "Mafa",
  "Magumeri",
  "Maiduguri",
  "Ngala",
  "Nganzai",
  "Shani",
  "Abi",
  "Akampka",
  "Akpabuyo",
  "Bakassi",
  "Bekwarra",
  "Biase",
  "Calabar Municipal",
  "Calabar South",
  "Ekureku",
  "Ikom",
  "Obanliku",
  "Obubra",
  "Odukpani",
  "Ogoja",
  "Yala",
  "Aniocha North",
  "Aniocha South",
  "Asaba",
  "Burutu",
  "Isoko North",
  "Isoko South",
  "Ika North East",
  "Ika South",
  "Okpe",
  "Oshimili North",
  "Oshimili South",
  "Patani",
  "Sapele",
  "Udu",
  "Ughelli North",
  "Ughelli South",
  "Warri North",
  "Warri South",
  "Warri South West",
  "Abakaliki",
  "Afikpo North",
  "Afikpo South",
  "Ebonyi",
  "Ezza North",
  "Ezza South",
  "Ikwo",
  "Ishielu",
  "Ivo",
  "Ohaozara",
  "Onicha",
  "Akoko-Edo",
  "Egor",
  "Esan Central",
  "Esan North-East",
  "Esan South-East",
  "Esan West",
  "Etsako Central",
  "Etsako East",
  "Etsako West",
  "Oredo",
  "Orhionmwon",
  "Ovia North-East",
  "Ovia South-West",
  "Uhunmwonde",
  "Ado Ekiti",
  "Ekiti East",
  "Ekiti South-West",
  "Ekiti West",
  "Emure",
  "Ilejemeje",
  "Irepodun/Ifelodun",
  "Isin",
  "Moba",
  "Oye",
  "Awgu",
  "Enugu East",
  "Enugu North",
  "Enugu South",
  "Ezeagu",
  "Igbo-Etiti",
  "Igboeze North",
  "Igboeze South",
  "Isi-Uzo",
  "Nkanu East",
  "Nkanu West",
  "Oji River",
  "Udi",
  "Uzo-Uwani",
  "Akko",
  "Balanga",
  "Billiri",
  "Dukku",
  "Funakaye",
  "Gombe",
  "Kaltungo",
  "Kwami",
  "Nafada",
  "Shongom",
  "Yamaltu/Deba",
  "Aboh Mbaise",
  "Ahiazu Mbaise",
  "Akokwa",
  "Dikenafai",
  "Ezinihitte",
  "Isu",
  "Mbaitoli",
  "Ngor Okpala",
  "Njaba",
  "Nwangele",
  "Obowo",
  "Oguta",
  "Ohaji/Egbema",
  "Orlu",
  "Orsu",
  "Owerri Municipal",
  "Owerri North",
  "Owerri West",
  "Ugwuta",
  "Birnin Gwari",
  "Chikun",
  "Giwa",
  "Igabi",
  "Ikara",
  "Jaba",
  "Jema'a",
  "Kachia",
  "Kaduna North",
  "Kaduna South",
  "Kagarko",
  "Kaura",
  "Kauru",
  "Kubau",
  "Lere",
  "Makarfi",
  "local-govt",
  "local-committees",
  "all",
];

export const regions = [
  {
    state: "in-market",
    location: [
      "balogun",
      "ikorodu",
      "agege",
      "ikotun",
      "mushin",
      "Mile12",
      "relief",
      "ochanja",
      "main-mkt",
      "agbeni",
      "ilorin",
      "cemetry-market",
      "mile1",
      "mile3",
      "benin",
      "uyo",
      "sabongari",
      "sokoto",
      "jos",
      "abuja",
      "central-market",
    ],
  },

  { state: "aba", location: ["aba-north", "aba-south", "osisioma-ngwa"] },

  {
    state: "oyo",
    location: [
      "ibadan-north",
      "ibadan-south-east",
      "ibadan-south-west",
      "ibadan-north-east",
      "oluyole",
      "ibadan-north-west",
      "ona-ara",
      "ido",
    ],
  },

  {
    state: "kano",
    location: [
      "dala",
      "fagge",
      "gwale",
      "kano-municipal",
      "kumbotso",
      "nassarawa",
      "tarauni",
      "ungogo",
    ],
  },

  {
    state: "onitsha",
    location: ["idemili-north", "ogbaru", "onitsha-north", "onitsha-south"],
  },

  {
    state: "lagos-out-market",
    location: [
      "ajeromi-ifelodun",
      "alimosho-a",
      "alimosho-b",
      "ikorodu",
      "kosofe",
      "mushin",
      "oshodi",
      "shomolu",
      "surulere",
      "yaba",
      "ikeja",
      "badagry",
      "lekki",
      "epe",
      "eti-osa",
      "ojo",
      "ifako-Ijaiye",
      "agege",
      "amuwo-odofin",
    ],
  },

  {
    state: "abuja",
    location: [
      "amac1",
      "amac2",
      "amac3",
      "amac4",
      "gwagwalada",
      "suleja",
      "karu-a",
      "karu-b",
    ],
  },

  {
    state: "port-harcourt",
    location: [
      "obio-akpor-a",
      "obio-akpor-b",
      "obio-akpor-c",
      "port-harcourt-city-a",
      "port-harcourt-city-b",
      "oyigbo",
    ],
  },

  {
    state: "ilorin",
    location: [
      "ilorin-east-a",
      "ilorin-east-b",
      "ilorin-south",
      "ilorin-west-a",
      "ilorin-west-b",
    ],
  },

  { state: "edo", lcation: ["benin"] },

  { state: "imo", location: ["owerri"] },

  { state: "cross-river", location: ["calabar"] },

  { state: "kaduna", location: ["kaduna", "zaria"] },

  { state: "plateau", location: ["jos"] },

  { state: "akwa-ibom", location: ["uyo"] },

  { state: "adamawa", location: ["yola"] },

  { state: "benue", location: ["makurdi"] },

  { state: "delta", location: ["asaba", "warri"] },

  { state: "enugu", location: ["enugu"] },

  { state: "ogun", location: ["abeokuta", "ado-odo-ota"] },

  { state: "katsina", location: ["katsina"] },

  { state: "abia", location: ["umuahia"] },

  { state: "ondo", location: ["akure"] },

  { state: "niger", location: ["minna"] },

  { state: "sokoto", location: ["sokoto"] },

  { state: "gombe", location: ["gombe"] },

  { state: "jigawa", location: ["dutse"] },
];
